### ISSUE TITLE
Unread message notification not working properly

### ISSUE THREAD

**Issue by Lighno** [CapnKitten/Material-Discord#61] opened 2019-10-04 14:25 UTC
The unread notification apears when you hover over a folders even when there's no unread message but doesn't apear on any server inside a folder even when it should

**Comment by CapnKitten** [comment] 2019-10-05 00:07
I know about the unread notification when hovering on server folders, but unread notifications should be working fine on servers inside folders.

**Comment by KaKi87** [comment] 2019-12-26 08:52
I'd also like to point out that currently selected folder is also marked as unread.

**Comment by KaKi87** [comment] 2019-12-26 10:51
There is also an incompatibility with [ServerFolders](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders)

**Comment by KaKi87** [comment] 2020-01-08 14:34
Hey there, any news on this ? Thanks

**Comment by CapnKitten** [comment] 2020-01-12 09:09
Haven't actively been working on the folders issue, sorry. Could you explain what the incompatibility is with ServerFolders? Thanks.

**Comment by KaKi87** [comment] 2020-01-12 16:19
## First issue, unrelated to ServerFolders :

The *pill* element is used for both *unread* **and** *selected* states while the user only see it as an *unread* state.

See figure below :

![2020-01-12 17_04_22-Greenshot](https://user-images.githubusercontent.com/21284089/72221735-9c602a00-355d-11ea-8161-68ea8c606a19.png)

- *green* captions indicate states properly interpreted by the user
- *red* captions indicate confusing states that should be fixed by the theme
-  *yellow* captions indicate that, despite your theme's behavior is misleading, the original one is too *(but you fixed it twice, so why not fix the rest too ? ^^)*

## Second issue, related to ServerFolders :

Far more simple : unread and selected states doesn't work.

![2020-01-12 17_18_34-Greenshot](https://user-images.githubusercontent.com/21284089/72221946-99fecf80-355f-11ea-9b67-9b3e047b0ba4.png)

Thanks

**Comment by CapnKitten** [comment] 2020-01-14 01:13
Due to the nature of how server unread notifications work and how I want them to look, I've made it somewhat work. There are still bugs that I have to figure out how to deal with, but you'll be able to see unread notifications in server folders with the plugin enabled. As for the folder hover and selected with the folder closed, I still have to fix that.

**Comment by KaKi87** [comment] 2020-01-14 07:55
I can confirm that the second issue is fixed. Thanks

**Comment by KaKi87** [comment] 2020-02-07 19:32
Hey @CapnKitten any news on this ?
Thanks

**Comment by CapnKitten** [comment] 2020-02-12 08:49
Sorry, I haven't had much time to delve more into this issue with all of the recent Discord updates.

**Comment by KaKi87** [comment] 2020-04-06 09:53
Hello,

Since the last update, unread badges no longer works on folders while ServerFolders is enabled.

Therefore, I firstly created an [issue on ServerFolders](https://github.com/mwittrien/BetterDiscordAddons/issues/405).

However, it seems that this issue is only happening with your theme, which I've just checked.

Thanks

**Comment by CapnKitten** [comment] 2020-04-07 03:11
Most plugins are based vanilla Discord, and Material Discord is a heavily customized theme so there can some times be incompatibility issues.

The unread notification has multiple uses in vanilla Discord; being the hovered server, selected server, and unread notification, which makes it annoying to work with and may cause issues with other plugins/themes that utilize said element(s). It is not intentional to make it not work plugins, it can just some times happen with the useless updates Discord pushes out.

Now you know why Material Discord might have incompatibility issues with other devs plugins/themes.

I'll get it fixed as soon as I can, thanks.

**Comment by KaKi87** [comment] 2020-07-29 20:36
Hello,

Any news on this ?

Thanks !

**Comment by CapnKitten** [comment] 2020-07-30 21:11
Sorry, it hasn't really been a focus point on the theme lately. I'll do some tinkering, possibly removing the styled notification icon altogether for the time being, unless I can figure out another way to do it.

**Closed** 2022-10-02 08:02 UTC
