### ISSUE TITLE
Certain letters get cut off by the message bubble

### ISSUE THREAD

**Issue by Eschate** [CapnKitten/Material-Discord#114] opened 2020-09-26 23:14 UTC
For examples lower-case j and p.
Appearance Settings:
Theme: Dark
Massage Display: Cozy
Chat Font size: 16
Space between Message groups: 16
Zoom level: 100
![Capture](https://user-images.githubusercontent.com/71949399/94351865-dee87900-0090-11eb-83e9-6a7991f13417.PNG)
(First letter supposed to be j)
No changes to message bubbles made in CSS.

**Comment by CapnKitten** [comment] 2020-09-27 00:35
I'm aware of this issue, currently trying to make the part that makes message bubbles look like one whole thing go behind the text.

**Comment by sjain882** [comment] 2020-10-06 14:40
This happens in the member list too, btw

**Comment by CapnKitten** [comment] 2020-10-06 18:38
Could you provide an example please?

**Comment by sjain882** [comment] 2020-10-15 15:26
> Could you provide an example please?

![image](https://user-images.githubusercontent.com/43217178/96151272-241b0080-0f03-11eb-854b-ba3eb899e5f0.png)

**Comment by CapnKitten** [comment] 2020-10-17 00:34
![a8BgdE](https://user-images.githubusercontent.com/4013216/96324252-dd0a3980-0fee-11eb-82aa-09642d44ed0d.png)
I'm unable to reproduce that. Are you using any other themes or plugins that I can toggle to see if I can make it happen?

**Comment by BobbyWibowo** [comment] 2020-10-25 07:51
If it helps, I reshaped the masks a while back for my own use, making them looking like these:
![Screenshot](https://i.fiery.me/0nvS9.png) ![Screenshot](https://i.fiery.me/5uXQ5.png)
The red-colored ones purely for visualization.
It was just a few parameter changes with the `border-width`.
https://gist.github.com/BobbyWibowo/9392103a4a831a669c1837c3fda88d62#file-materialdiscordcustom-theme-css-L107-L124
I can't be sure if it'll end up behaving differently depending on the platforms and/or fonts however, but they look fine on my end.

**Comment by CapnKitten** [comment] 2020-10-25 08:07
I can implement it that way, thanks.

**Comment by CapnKitten** [comment] 2020-10-31 06:22
Implemented the fix by @BobbyWibowo and will be in the next update.

**Comment by CapnKitten** [comment] 2020-11-03 00:50
Update is live.

**Closed by CapnKitten** 2020-11-03 00:50 UTC
